# Generated by Django 3.1.2 on 2020-10-21 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meme',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meme',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='memes/'),
        ),
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meme',
            name='title',
            field=models.CharField(default='title', max_length=150, unique=True),
        ),
    ]
