version: "3.7"

services:
  django_web:
    build: ./django_backend
    command: sh docker-entrypoint.dev.sh
    volumes:
      - ./django_backend/:/usr/src/django_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  react_frontend:
    stdin_open: true
    build: ./react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react_frontend/:/usr/src/react_frontend/
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
  react_frontend: